add_compile_definitions(
    CPU
    PY311
)

set(OPENCV_GPU OFF)
set(IK_VOLUME_RENDER ON)
set(PRODUCTION OFF)
set(IKOMIA_TESTS OFF)
set(IKOMIA_TESTS_CL OFF)
set(PYTHON_VERSION_DOT 3.11)
set(PYTHON_VERSION_DOT_M 3.11)
set(PYTHON_VERSION_NO_DOT 311)

if(WIN32)
    set(BOOST_VERSION 1.88.0)
    set(BOOST_VC_VERSION 143)
    set(MSVC_VERSION 17)
    set(CUDA_VERSION 12.1)
endif()
